### ISSUE TITLE
caputRecorder does not build with base 7.0.5

### ISSUE THREAD

**Issue by MarkRivers** [epics-modules/caputRecorder#4]
I am trying to build synApps for the first time with base 7.0.5.  caputRecorder fails to build with the following error.  I am on the master branch.

```
/usr/bin/gcc  -D_GNU_SOURCE -D_DEFAULT_SOURCE           -D_X86_  -DUNIX  -Dlinux      -O3 -g   -Wall -Werror-implicit-function-declaration     -DUSE_TYPED_RSET  -mtune=generic      -m32 -D_FILE_OFFSET_BITS=64 -fPIC -I. -I../O.Common -I. -I. -I.. -I../../../include/compiler/gcc -I../../../include/os/Linux -I../../../include    -I/corvette/usr/local/epics-devel/base-7.0.5/include/compiler/gcc -I/corvette/usr/local/epics-devel/base-7.0.5/include/os/Linux -I/corvette/usr/local/epics-devel/base-7.0.5/include        -c ../subMLIS.c
../subMLIS.c:20:16: error: redefinition of 'struct evSubscrip'
 typedef struct evSubscrip {
                ^
In file included from /corvette/usr/local/epics-devel/base-7.0.5/include/dbChannel.h:26:0,
                 from /corvette/usr/local/epics-devel/base-7.0.5/include/dbLink.h:24,
                 from /corvette/usr/local/epics-devel/base-7.0.5/include/dbAccess.h:25,
                 from ../subMLIS.c:8:
/corvette/usr/local/epics-devel/base-7.0.5/include/dbEvent.h:42:8: note: originally defined here
 struct evSubscrip;
        ^
make[3]: *** [subMLIS.o] Error 1
make[3]: Leaving directory `/home/epics/devel/caputRecorder-1-7-2/caputRecorderApp/src/O.linux-x86'
make[2]: *** [install.linux-x86] Error 2
make[2]: Leaving directory `/home/epics/devel/caputRecorder-1-7-2/caputRecorderApp/src'
make[1]: *** [src.install] Error 2
make[1]: Leaving directory `/home/epics/devel/caputRecorder-1-7-2/caputRecorderApp'
make: *** [caputRecorderApp.install] Error 2
corvette:~/devel/caputRecorder>
```

**Comment by anjohnson** [comment]
While @MarkRivers resolved the build issue with his PR #5 the result could easily break with future releases of Base. It looks like the existing code should be okay, but the definition of `struct evSubscrip` changed between 3.14 and 3.15 and the definition in subMLIS.c matches the version in 3.14. Both versions start with an `ELLNODE node` which is the only member used in this code, but any modifications to subMLIS.c that start accessing the `paddr` field say will not work.

The definition of `struct evSubscrip` was made public and moved into the new dbChannel.h header in the 3.15.0.1 release, so I suggest enclosing the definition of `struct evSubscrip` inside a test for EPICS version <3.15.0.1 and including the dbChannel.h header for this declaration instead for later EPICS versions. I would probably also delete the `paddr` data member since there is no equivalent in the 3.15 and later version, it became a `dbChannel *chan` instead.
